### ISSUE TITLE
About the converge of Pruning network

### ISSUE THREAD

**Issue by pecanjk** [liuzechun/MetaPruning#12]
Random input to the Pruning network. I wonder if it can converge. In the hypernetwork paper, the input are fixed. Besides. it seems you use lots of independent small FC layers network instead of use a fixed same hypernetwork as a Pruning network. Lots of small Pruning network not one fixed Pruning work. Is this the meta learning way?

**Comment by liuzechun** [comment]
Each pruning net block is for generating the weights for each layer of the pruned network (with different channel number choices). Using the same pruning net block for every layer of the pruned network is not feasible because the weights in the pruning net block is not so powerful to generate weights for so many different pruned networks.
